# Generated by Django 2.2.1 on 2019-05-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndianPincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.TextField(help_text='Office Name', verbose_name='Office Name')),
                ('pin_code', models.IntegerField(help_text='Pincode', verbose_name='Pincode')),
                ('office_type', models.TextField(help_text='Office Type', verbose_name='Office Type')),
                ('delivery_status', models.CharField(help_text='Delivery Status', max_length=100, verbose_name='Delivery Status')),
                ('division_name', models.TextField(help_text='Division', verbose_name='Division Name')),
                ('region_name', models.TextField(help_text='Region', verbose_name='Region Name')),
                ('circle_name', models.TextField(help_text='Circle', verbose_name='Circle Name')),
                ('taluk', models.TextField(help_text='Taluk', verbose_name='Taluk Name')),
                ('district_name', models.TextField(help_text='District', verbose_name='District Name')),
                ('state_name', models.TextField(help_text='State', verbose_name='State Name')),
            ],
            options={
                'db_table': 'indian_pincode',
            },
        ),
    ]
